"""empty message

Revision ID: 306346318e45
Revises: 45ebd74522b4
Create Date: 2023-10-31 02:01:51.500156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306346318e45'
down_revision = '45ebd74522b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('logo', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
