"""empty message

Revision ID: 3d533e32aa76
Revises: 631e13e328d2
Create Date: 2023-11-08 06:06:56.451689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d533e32aa76'
down_revision = '631e13e328d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_Producto', sa.Integer(), nullable=False),
    sa.Column('id_User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Producto'], ['product.id'], ),
    sa.ForeignKeyConstraint(['id_User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito')
    # ### end Alembic commands ###
