"""empty message

Revision ID: 46199482ec23
Revises: 
Create Date: 2023-11-10 08:23:16.244830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46199482ec23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=320), nullable=True),
    sa.Column('idu', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('idu', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('contacto', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=250), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('contacto', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_Producto', sa.Integer(), nullable=False),
    sa.Column('id_User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Producto'], ['product.id'], ),
    sa.ForeignKeyConstraint(['id_User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito')
    op.drop_table('user')
    op.drop_table('sucursales')
    op.drop_table('restaurantes')
    op.drop_table('product')
    op.drop_table('categorias')
    # ### end Alembic commands ###
