"""empty message

Revision ID: 568f8bb87bdc
Revises: 35b7578ed491
Create Date: 2023-11-08 04:44:33.230419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568f8bb87bdc'
down_revision = '35b7578ed491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('idu', sa.String(length=80), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('idu')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
