"""empty message

Revision ID: 59d64d97bf91
Revises: 392531b73e38
Create Date: 2023-11-13 15:16:02.442385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d64d97bf91'
down_revision = '392531b73e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dir', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=250), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('dir')

    # ### end Alembic commands ###
