"""empty message

Revision ID: 5d7d6f7c017a
Revises: 46199482ec23
Create Date: 2023-11-10 18:57:34.610507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7d6f7c017a'
down_revision = '46199482ec23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('url_img', sa.String(length=320), nullable=False),
    sa.Column('idu_img', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('url_img', sa.String(length=250), nullable=False),
    sa.Column('idu_img', sa.String(length=250), nullable=False),
    sa.Column('name_contact', sa.String(length=250), nullable=False),
    sa.Column('num_contact', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('name_contact', sa.String(length=250), nullable=False),
    sa.Column('num_contact', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id_Product', sa.Integer(), nullable=False),
    sa.Column('id_User', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['id_User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('carrito')
    op.drop_table('sucursales')
    op.drop_table('restaurantes')
    op.drop_table('categorias')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('idu_img', sa.String(length=250), nullable=True))
        batch_op.drop_column('idu')
        batch_op.drop_column('img')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idu', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('idu_img')
        batch_op.drop_column('url_img')

    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('idu', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categorias_pkey')
    )
    op.create_table('restaurantes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('contacto', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='restaurantes_pkey')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('contacto', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sucursales_pkey')
    )
    op.create_table('carrito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_Producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_User', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_Producto'], ['product.id'], name='carrito_id_Producto_fkey'),
    sa.ForeignKeyConstraint(['id_User'], ['user.id'], name='carrito_id_User_fkey'),
    sa.PrimaryKeyConstraint('id', name='carrito_pkey')
    )
    op.drop_table('cart')
    op.drop_table('sucursale')
    op.drop_table('restaurant')
    op.drop_table('category')
    # ### end Alembic commands ###
