"""empty message

Revision ID: 674fd16dc5d8
Revises: a69e1941a4ed
Create Date: 2023-11-14 05:25:55.734993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674fd16dc5d8'
down_revision = 'a69e1941a4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_id_Order_fkey', type_='foreignkey')
        batch_op.drop_column('id_Order')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cart_id_Order_fkey', 'order', ['id_Order'], ['id'])

    # ### end Alembic commands ###
