"""empty message

Revision ID: 6888e42eee01
Revises: 298aada42434
Create Date: 2023-11-05 07:13:46.255546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6888e42eee01'
down_revision = '298aada42434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=250), nullable=True))
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
