"""empty message

Revision ID: a293385a1402
Revises: 27481d7c8c53
Create Date: 2023-11-01 00:26:37.078300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a293385a1402'
down_revision = '27481d7c8c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
