"""empty message

Revision ID: a69e1941a4ed
Revises: df810a003c6b
Create Date: 2023-11-14 03:04:01.293976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69e1941a4ed'
down_revision = 'df810a003c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Order', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['id_Order'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_Order')

    # ### end Alembic commands ###
