"""empty message

Revision ID: a78119e944f0
Revises: 94a7d0b88ea1
Create Date: 2023-11-12 07:14:48.527482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78119e944f0'
down_revision = '94a7d0b88ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Restaurant', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'restaurant', ['id_Restaurant'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_Restaurant')

    # ### end Alembic commands ###
