"""empty message

Revision ID: c208bb57f5ba
Revises: 674fd16dc5d8
Create Date: 2023-11-14 05:26:37.640796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c208bb57f5ba'
down_revision = '674fd16dc5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Order', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['id_Order'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_Order')

    # ### end Alembic commands ###
