"""empty message

Revision ID: d1a5a61ce495
Revises: 802713279f8b
Create Date: 2023-11-16 02:03:17.919628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a5a61ce495'
down_revision = '802713279f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('idu_img')
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('idu_img', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
