"""empty message

Revision ID: e011e737df77
Revises: d1a5a61ce495
Create Date: 2023-11-16 03:51:13.039499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e011e737df77'
down_revision = 'd1a5a61ce495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_category', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['id_category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_category')

    # ### end Alembic commands ###
