"""empty message

Revision ID: eb1b33d3706f
Revises: 5d7d6f7c017a
Create Date: 2023-11-10 22:23:35.864565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1b33d3706f'
down_revision = '5d7d6f7c017a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('idu_img', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursale', schema=None) as batch_op:
        batch_op.drop_column('idu_img')
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###
